#String MessageLogger::kUnknownName   = "UNKNOWN";
#String MessageLogger::kTraceName     = "TRACE";;
#String MessageLogger::kEndName       = "ENDF";
#String MessageLogger::kStartName     = "STARTF";
#String MessageLogger::kDebug0Name    = "DEBUG0";
#String MessageLogger::kDebug1Name    = "DEBUG1";
#String MessageLogger::kDebug2Name    = "DEBUG2";
#String MessageLogger::kInfoName      = "INFO";
#String MessageLogger::kWarningName   = "WARNING";
#String MessageLogger::kErrorName     = "ERROR";
#String MessageLogger::kFatalName     = "FATAL";
#
# ==================
# RunAnalysis
# ==================
RunAnalysis:TASK:NAME                = RunAnalysis
RunAnalysis:TASK:CLASS = CAP::EventIterator
RunAnalysis:TASK:SEVERITY            = TRACE
RunAnalysis:SUBTASK:N                = 2
RunAnalysis:SUBTASK_0:NAME           = GlauberGenerator
RunAnalysis:SUBTASK_1:NAME           = GlauberAnalyzer
RunAnalysis:EVENT:USE                = 1
RunAnalysis:EVENT:CREATE             = 1
RunAnalysis:EVENT:REQUESTED:N        = 100000
RunAnalysis:EVENT:REPORT:N           = 1000
RunAnalysis:EVENT:N                  = 1
RunAnalysis:EVENT_0:NAME             = TOY
RunAnalysis:EVENT_0:OWNER            = 1

GlauberGenerator:TASK:NAME                = GlauberGenerator
GlauberGenerator:TASK:CLASS               = CAP::GlauberGenerator
GlauberGenerator:TASK:SEVERITY            = TRACE
GlauberGenerator:SUBTASK:N                = 0
GlauberGenerator:EVENT:USE                = 1
GlauberGenerator:EVENT:N                  = 1
GlauberGenerator:EVENT_0:NAME             = Glauber
GlauberGenerator:EVENT_0:OWNER            = 1

GlauberGenerator:DB:USE                   = 1
GlauberGenerator:DB:CREATE               = 0
GlauberGenerator:DB:IMPORT               = 0
GlauberGenerator:DB:EXPORT               = 0
GlauberGenerator:DB:N                    = 1
GlauberGenerator:DB_0:NAME               = DefaultDb
GlauberGenerator:DB_0:TITLE              = DefaultDb
GlauberGenerator:DB_0:OWNER              = 1

GlauberGenerator:GENERATION:NUCLEUS_A:NAME                = Pb
GlauberGenerator:GENERATION:NUCLEUS_A:NTRIALS             = 40
GlauberGenerator:GENERATION:NUCLEUS_A:RECENTERING         = true
GlauberGenerator:GENERATION:NUCLEUS_A:ALLOW_OVERLAP.      = true
GlauberGenerator:GENERATION:NUCLEUS_B:NAME                = Pb
GlauberGenerator:GENERATION:NUCLEUS_B:NTRIALS             = 40
GlauberGenerator:GENERATION:NUCLEUS_B:RECENTERING.        = true
GlauberGenerator:GENERATION:NUCLEUS_B:ALLOW_OVERLAP       = true

GlauberGenerator:GENERATION:INTERACTION:NNCOLLISION_OPTION = 1
GlauberGenerator:GENERATION:INTERACTION:xSECT_OPTION       = 1
GlauberGenerator:GENERATION:INTERACTION:IMPACT_MIN         = 0.0
GlauberGenerator:GENERATION:INTERACTION:IMPACT_MAX         = 20.0
GlauberGenerator:GENERATION:INTERACTION:RANDOMIZE_EP       = 0
GlauberGenerator:GENERATION:INTERACTION:SQRT_S             = 13000.0
GlauberGenerator:GENERATION:INTERACTION:SQRT_S_OPTION      = 1
GlauberGenerator:GENERATION:INTERACTION:xSECTION           = 60.0
GlauberGenerator:GENERATION:INTERACTION:xSECTION_SIGMA     = 1.0
GlauberGenerator:GENERATION:INTERACTION:xSECTION_OMEGA     = 1.0
GlauberGenerator:GENERATION:INTERACTION:xSECTION_G         = 1.0
GlauberGenerator:GENERATION:INTERACTION:DISTANCE_MAX       = 3.0
GlauberGenerator:GENERATION:INTERACTION:HARD_DISTANCE_MAX  = 0.4
GlauberGenerator:GENERATION:INTERACTION:SMEARINGPROFILE:NUCLEONSIGMA   = 1.0
#GlauberGenerator:GENERATION:PTOTPROFILE:NNXSECT            = 1.0
#GlauberGenerator:GENERATION:PTOTPROFILE:NNXSECTOMEGA       = 1.0
#GlauberGenerator:GENERATION:PTOTPROFILE:NNXSECTLAMBDA      = 1.0
GlauberGenerator:GENERATION:NUCLEONPROFILE:NUCLEONRADIUS   = 1.0

GlauberAnalyzer:TASK:NAME                = GlauberAnalyzer
GlauberAnalyzer:TASK:CLASS               = CAP::GlauberAnalyzer
GlauberAnalyzer:TASK:SEVERITY            = TRACE
GlauberAnalyzer:SUBTASK:N                = 0
GlauberAnalyzer:EVENT:USE                = 1
GlauberAnalyzer:EVENT:N                  = 1
GlauberAnalyzer:EVENT_0:NAME             = Glauber

GlauberAnalyzer:HISTOGRAM:USE          = 1
GlauberAnalyzer:HISTOGRAM:N                    = 1
GlauberAnalyzer:HISTOGRAM:IMPORT               = 0
GlauberAnalyzer:HISTOGRAM:CREATE               = 1
GlauberAnalyzer:HISTOGRAM:EXPORT               = 1
GlauberAnalyzer:HISTOGRAM:SCALE                = 1
GlauberAnalyzer:HISTOGRAM:IMPORT:PATH          = DEFAULT
GlauberAnalyzer:HISTOGRAM:IMPORT:FILE_NAME     = DEFAULT
GlauberAnalyzer:HISTOGRAM:EXPORT:BASE_NAME     = GB
GlauberAnalyzer:HISTOGRAM:EXPORT:PATH          = DEFAULT
GlauberAnalyzer:HISTOGRAM:EXPORT:FILE_NAME     = Glauber.root
GlauberAnalyzer:HISTOGRAM:EXPORT:FORCE_REWRITE = 0

GlauberAnalyzer:HISTOGRAM_0:NAME               = GB
GlauberAnalyzer:HISTOGRAM_0:BASE_NAME          = GB
GlauberAnalyzer:HISTOGRAM_0:OWNER              = 1


GlauberAnalyzer:HISTOGRAM:fillBasics      = 1
GlauberAnalyzer:HISTOGRAM:fillMoments      = 1
GlauberAnalyzer:HISTOGRAM:fillSmeared      = 1
GlauberAnalyzer:HISTOGRAM:nOrders          = 4
GlauberAnalyzer:HISTOGRAM:nParts_nBins      = 250
GlauberAnalyzer:HISTOGRAM:nBinaries_nBins   = 200
GlauberAnalyzer:HISTOGRAM:nSpect_nBins      = 250
GlauberAnalyzer:HISTOGRAM:impact_nBins      = 100
GlauberAnalyzer:HISTOGRAM:cs_nBins          = 100
GlauberAnalyzer:HISTOGRAM:psi_nBins         = 100
GlauberAnalyzer:HISTOGRAM:ecc_nBins         = 100
GlauberAnalyzer:HISTOGRAM:rn_nBins          = 100
GlauberAnalyzer:HISTOGRAM:psiN_nBins        = 100
GlauberAnalyzer:HISTOGRAM:eccN_nBins       = 100

GlauberAnalyzer:HISTOGRAM:nParts_min        = 0
GlauberAnalyzer:HISTOGRAM:nBinaries_min     = 0
GlauberAnalyzer:HISTOGRAM:nSpect_min        = 0
GlauberAnalyzer:HISTOGRAM:impact_min        = 0
GlauberAnalyzer:HISTOGRAM:cs_min            = 0
GlauberAnalyzer:HISTOGRAM:psi_min           = 0
GlauberAnalyzer:HISTOGRAM:ecc_min           = 0
GlauberAnalyzer:HISTOGRAM:rn_min            = 0
GlauberAnalyzer:HISTOGRAM:psiN_min          = 0
GlauberAnalyzer:HISTOGRAM:eccN_min          = 0


GlauberAnalyzer:HISTOGRAM:nParts_max        = 500
GlauberAnalyzer:HISTOGRAM:nBinaries_max     = 5000
GlauberAnalyzer:HISTOGRAM:nSpect_max        = 500
GlauberAnalyzer:HISTOGRAM:impact_max        = 20
GlauberAnalyzer:HISTOGRAM:cs_max       = 10
GlauberAnalyzer:HISTOGRAM:psi_max      = 10
GlauberAnalyzer:HISTOGRAM:ecc_max      = 10
GlauberAnalyzer:HISTOGRAM:rn_max       = 10
GlauberAnalyzer:HISTOGRAM:psiN_max     = 10
GlauberAnalyzer:HISTOGRAM:eccN_max     = 10


GlauberAnalyzer:HISTOGRAM:DO_PATH_LENGTH    = 0
GlauberAnalyzer:HISTOGRAM:DO_AREA           = 0
GlauberAnalyzer:HISTOGRAM:DO_CORE           = 0

