/* **********************************************************************
 * Copyright (C) 2019-2024, Claude Pruneau, Victor Gonzalez
 * All rights reserved.
 *
 * Based on the ROOT package and environment
 *
 * For the licensing terms see LICENSE.
 *
 * Author: Claude Pruneau,   04/01/2024
 *
 * *********************************************************************/
#ifndef CAP__Task
#define CAP__Task
#include "ConfigurationManager.hpp"
#include "Accountant.hpp"
#include "Object.hpp"
#include "Timer.hpp"
#include <iostream>
namespace CAP
{

  class Task
  :
  public Object,
  public ConfigurationManager
  {
  public:

  Task();
  Task(const Task & task);
  Task & operator=(const Task & task);
  virtual ~Task();

  virtual void setDefaultConfiguration();
  virtual void configure(const Configuration & configuration);
  virtual void initialize();
  virtual void execute();
  virtual void postProcess();
  virtual void partial();
  virtual void finalize();
  virtual void reset();
  virtual void clear();
  virtual void print() const;
  virtual void configureSubtasks(Task * task,
                                 const String & parentTaskName,
                                 const Configuration & configuration);

  void initializeSubTasks();
  void executeSubTasks();
  void finalizeSubTasks();
  void partialSubTasks();
  void resetSubTasks();
  void clearSubTasks();
  void printSubTasks() const;

  std::vector<Task*> & subTasks()  { return _subTasks; }
  const std::vector<Task*> & subTaks() const  { return _subTasks; }
  bool hasSubTasks()  const  { return _subTasks.size()>0;  }
  unsigned int nSubTasks() const  { return _subTasks.size(); }
  Task * subTaskAt(unsigned int index);
  Task * addSubTask(Task * task);

  String parentTaskName() const   { return _parentTask->name(); }
  bool hasParent() const  {   return _parentTask!=nullptr; }
  Task * parentTask() const  {   return _parentTask; }
  void setParentTask(Task * parent)  { _parentTask = parent; }
  String parentName() const;
  Task * taskAt(int depth);
  const Task * taskAt(int depth) const;
  String reverseTaskPath(int depth=0) const;
  std::vector<String> taskPathTokens() const;
  String taskPath(int depth=0) const;
  String fullTaskPath() const;
  int nAncestors() const;

  Task * createTask(Task * _parentTask,
                    const String & taskName,
                    const Configuration & configuration);

  Accountant & taskExecuted() { return _taskExecuted; }
  const Accountant & taskExecuted() const { return _taskExecuted; }
  void incrementTaskExecuted() { _taskExecuted.increment(); }

  protected:

  //!
  //! Pointer to parent task if any
  //!
  Task * _parentTask;

  //!
  //! Array of pointers to subTasks called by this task instance, once per event analyzed (or iteration generated by EventIterator task). If this instance carries out
  //! initialize, finalize, execute type operations, these are performed BEFORE the corresponding operations by the subTasks.
  //!
  std::vector<Task*> _subTasks;

  //!
  //! Use an accountant instance to keep track of the number of times the "execute" function is called.
  //!
  Accountant _taskExecuted;

  //!
  //! Use time to keep track of executioin time
  //!
  Timer _timer;

  ClassDef(Task,0)
  };

}

#endif /* CAP__Task */
